### ISSUE TITLE
rename from "tomill/maji" to "tomill/majimaji"

### ISSUE THREAD

**Issue by mumumu** [tomill/maji#1]
> "Maji maji" means "watching carefully" in Japanese.

"maji" itself means "really?" in Japanese, you know. From "tomill/maji" namespace, I could not come across "Maji maji" meaning. 

For clarification, How about rename its name "maji" to "majimaji" ? What do you think?

**Comment by tomill** [comment]
Hi mumumu :)

Its a good PoV, thank you

Actually, this name has not much meaning (I've just avoid an existing binary names). and in my opinion short one is better than long one  especially in cli world.

then I just updated readme.
